import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation } from "@/app/components/nav";
import { ProductsProvider } from "@/app/providers/products";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className={`${inter.className} typography`}>
        <Navigation />
        <div className="my-12 w-full">{children}</div>
      </body>
    </html>
  );
}
